# Generated by Django 3.1.5 on 2021-01-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
